// Code generated by protoc-gen-go. DO NOT EDIT.
// source: screen_message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Screen_Panel int32

const (
	Screen_UNKNOWN Screen_Panel = 0
	Screen_IPS     Screen_Panel = 1
	Screen_OLED    Screen_Panel = 2
)

var Screen_Panel_name = map[int32]string{
	0: "UNKNOWN",
	1: "IPS",
	2: "OLED",
}
var Screen_Panel_value = map[string]int32{
	"UNKNOWN": 0,
	"IPS":     1,
	"OLED":    2,
}

func (x Screen_Panel) String() string {
	return proto.EnumName(Screen_Panel_name, int32(x))
}
func (Screen_Panel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_screen_message_9226fe5473458884, []int{0, 0}
}

type Screen struct {
	SizeInch             float32             `protobuf:"fixed32,1,opt,name=size_inch,json=sizeInch,proto3" json:"size_inch,omitempty"`
	Resolution           *Screen_Resolustion `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Panel                Screen_Panel        `protobuf:"varint,3,opt,name=panel,proto3,enum=pcbook.Screen_Panel" json:"panel,omitempty"`
	Multitouch           bool                `protobuf:"varint,4,opt,name=multitouch,proto3" json:"multitouch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Screen) Reset()         { *m = Screen{} }
func (m *Screen) String() string { return proto.CompactTextString(m) }
func (*Screen) ProtoMessage()    {}
func (*Screen) Descriptor() ([]byte, []int) {
	return fileDescriptor_screen_message_9226fe5473458884, []int{0}
}
func (m *Screen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Screen.Unmarshal(m, b)
}
func (m *Screen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Screen.Marshal(b, m, deterministic)
}
func (dst *Screen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Screen.Merge(dst, src)
}
func (m *Screen) XXX_Size() int {
	return xxx_messageInfo_Screen.Size(m)
}
func (m *Screen) XXX_DiscardUnknown() {
	xxx_messageInfo_Screen.DiscardUnknown(m)
}

var xxx_messageInfo_Screen proto.InternalMessageInfo

func (m *Screen) GetSizeInch() float32 {
	if m != nil {
		return m.SizeInch
	}
	return 0
}

func (m *Screen) GetResolution() *Screen_Resolustion {
	if m != nil {
		return m.Resolution
	}
	return nil
}

func (m *Screen) GetPanel() Screen_Panel {
	if m != nil {
		return m.Panel
	}
	return Screen_UNKNOWN
}

func (m *Screen) GetMultitouch() bool {
	if m != nil {
		return m.Multitouch
	}
	return false
}

type Screen_Resolustion struct {
	Width                uint32   `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Screen_Resolustion) Reset()         { *m = Screen_Resolustion{} }
func (m *Screen_Resolustion) String() string { return proto.CompactTextString(m) }
func (*Screen_Resolustion) ProtoMessage()    {}
func (*Screen_Resolustion) Descriptor() ([]byte, []int) {
	return fileDescriptor_screen_message_9226fe5473458884, []int{0, 0}
}
func (m *Screen_Resolustion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Screen_Resolustion.Unmarshal(m, b)
}
func (m *Screen_Resolustion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Screen_Resolustion.Marshal(b, m, deterministic)
}
func (dst *Screen_Resolustion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Screen_Resolustion.Merge(dst, src)
}
func (m *Screen_Resolustion) XXX_Size() int {
	return xxx_messageInfo_Screen_Resolustion.Size(m)
}
func (m *Screen_Resolustion) XXX_DiscardUnknown() {
	xxx_messageInfo_Screen_Resolustion.DiscardUnknown(m)
}

var xxx_messageInfo_Screen_Resolustion proto.InternalMessageInfo

func (m *Screen_Resolustion) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Screen_Resolustion) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Screen)(nil), "pcbook.Screen")
	proto.RegisterType((*Screen_Resolustion)(nil), "pcbook.Screen.Resolustion")
	proto.RegisterEnum("pcbook.Screen_Panel", Screen_Panel_name, Screen_Panel_value)
}

func init() {
	proto.RegisterFile("screen_message.proto", fileDescriptor_screen_message_9226fe5473458884)
}

var fileDescriptor_screen_message_9226fe5473458884 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x4d, 0xd7, 0x76, 0xf5, 0x2b, 0x93, 0xf2, 0x51, 0xa4, 0x4c, 0x90, 0xb2, 0x8b, 0xc5,
	0x43, 0x0f, 0xf3, 0xa6, 0x37, 0xd1, 0xc3, 0x50, 0xba, 0x91, 0x21, 0x82, 0x97, 0xb1, 0xd6, 0xb0,
	0x06, 0xbb, 0xa4, 0x34, 0x29, 0x82, 0xff, 0x86, 0xff, 0xb0, 0x34, 0xf1, 0x50, 0x76, 0x7c, 0x2f,
	0xbf, 0xbc, 0xf7, 0xf8, 0x20, 0x56, 0x55, 0xc7, 0x98, 0xd8, 0x1d, 0x99, 0x52, 0xfb, 0x03, 0xcb,
	0xdb, 0x4e, 0x6a, 0x89, 0x7e, 0x5b, 0x95, 0x52, 0x7e, 0x2d, 0x7e, 0x1d, 0xf0, 0xb7, 0x06, 0xc0,
	0x2b, 0x38, 0x57, 0xfc, 0x87, 0xed, 0xb8, 0xa8, 0xea, 0x84, 0xa4, 0x24, 0x73, 0x68, 0x30, 0x18,
	0x2b, 0x51, 0xd5, 0x78, 0x0f, 0xd0, 0x31, 0x25, 0x9b, 0x5e, 0x73, 0x29, 0x12, 0x27, 0x25, 0x59,
	0xb8, 0x9c, 0xe7, 0x36, 0x24, 0xb7, 0x01, 0x39, 0x35, 0x80, 0x1a, 0x08, 0x3a, 0xa2, 0xf1, 0x16,
	0xbc, 0x76, 0x2f, 0x58, 0x93, 0x4c, 0x52, 0x92, 0x5d, 0x2c, 0xe3, 0x93, 0x6f, 0x9b, 0xe1, 0x8d,
	0x5a, 0x04, 0xaf, 0x01, 0x8e, 0x7d, 0xa3, 0xb9, 0x96, 0x7d, 0x55, 0x27, 0x6e, 0x4a, 0xb2, 0x80,
	0x8e, 0x9c, 0xf9, 0x03, 0x84, 0xa3, 0x1a, 0x8c, 0xc1, 0xfb, 0xe6, 0x9f, 0xda, 0xee, 0x9d, 0x51,
	0x2b, 0xf0, 0x12, 0xfc, 0x9a, 0xf1, 0x43, 0xad, 0xcd, 0xd0, 0x19, 0xfd, 0x57, 0x8b, 0x1b, 0xf0,
	0x4c, 0x19, 0x86, 0x30, 0x7d, 0x2b, 0x5e, 0x8a, 0xf5, 0x7b, 0x11, 0x9d, 0xe1, 0x14, 0x26, 0xab,
	0xcd, 0x36, 0x22, 0x18, 0x80, 0xbb, 0x7e, 0x7d, 0x7e, 0x8a, 0x9c, 0x47, 0xf7, 0xc3, 0x69, 0xcb,
	0xd2, 0x37, 0xa7, 0xba, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xea, 0x81, 0x5d, 0x66, 0x42, 0x01,
	0x00, 0x00,
}
